name: lambda-calculator
version: 0.1.0.0
github: "I-Al-Istannen/lambda-calculator"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2020 I-Al-Istannen"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/I-Al-Istannen/lambda-calculator#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec

library:
  source-dirs: src

executables:
  lambda-calculator:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-calculator
